# Generated by Django 3.1.7 on 2021-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='STATUS',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('EM VISITA', 'Em visita'), ('FINALIZADO', 'Visita finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='hoaraio_autorizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horario de autorização de entrada'),
        ),
    ]
