# Generated by Django 3.1.7 on 2021-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_rename_registrador_por_visitantes_registrado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitantes',
            old_name='registrado_por',
            new_name='registrador_por',
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='STATUS',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('EM VISITA', 'Em visita'), ('FINALIZADO', 'Visita finalizada')], default='Aguardando', max_length=10, verbose_name='Status'),
        ),
    ]
