# Generated by Django 3.1.7 on 2021-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_auto_20211007_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='STATUS',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando autorização'), ('EM_VISITA', 'Em visita'), ('FINALIZADO', 'Visita finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status'),
        ),
    ]
