# Generated by Django 3.1.7 on 2021-10-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteiro',
            options={'verbose_name': 'Adm Junior', 'verbose_name_plural': 'Porteiros'},
        ),
    ]
